package com.discord.tti_manager;

import com.discord.logging.Log;
import com.discord.react.utilities.NativeArrayExtensionsKt;
import com.discord.react.utilities.NativeMapExtensionsKt;
import com.discord.tti_manager.TTIMetrics;
import com.discord.tti_manager.react.ReactMarkerListener;
import com.facebook.react.bridge.BaseJavaModule;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import java.util.ArrayList;
import java.util.Map;
import kg.x;
import kotlin.Metadata;
import kotlin.collections.k;
import kotlin.jvm.internal.q;
import lg.v;

@Metadata(d1 = {"\u00006\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010%\n\u0002\u0010\u000e\n\u0002\u0010\t\n\u0002\b\u0006\n\u0002\u0010\u000b\n\u0002\b\u0002\u0018\u00002\u00020\u0001B\r\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0002\u0010\u0004J\u0010\u0010\u0005\u001a\u00020\u00062\u0006\u0010\u0007\u001a\u00020\bH\u0007J\u0014\u0010\t\u001a\u000e\u0012\u0004\u0012\u00020\u000b\u0012\u0004\u0012\u00020\f0\nH\u0016J\u0010\u0010\r\u001a\u00020\u00062\u0006\u0010\u0007\u001a\u00020\bH\u0007J\b\u0010\u000e\u001a\u00020\u000bH\u0016J\u0010\u0010\u000f\u001a\u00020\u00062\u0006\u0010\u0010\u001a\u00020\u000bH\u0007J\u0010\u0010\u0011\u001a\u00020\u00062\u0006\u0010\u0007\u001a\u00020\bH\u0007J\b\u0010\u0012\u001a\u00020\u0013H\u0007J\b\u0010\u0014\u001a\u00020\u0006H\u0007¨\u0006\u0015"}, d2 = {"Lcom/discord/tti_manager/TTIManagerModule;", "Lcom/facebook/react/bridge/ReactContextBaseJavaModule;", "reactContext", "Lcom/facebook/react/bridge/ReactApplicationContext;", "(Lcom/facebook/react/bridge/ReactApplicationContext;)V", "getAllNativeTimestamps", "", BaseJavaModule.METHOD_TYPE_PROMISE, "Lcom/facebook/react/bridge/Promise;", "getConstants", "", "", "", "getJSBundleTimestamps", "getName", "logToDevice", "value", "logToDeviceEnabled", "runningTTIAutomation", "", "trackTTILogged", "tti_manager_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
/* loaded from: classes6.dex */
public final class TTIManagerModule extends ReactContextBaseJavaModule {
    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public TTIManagerModule(ReactApplicationContext reactContext) {
        super(reactContext);
        q.g(reactContext, "reactContext");
    }

    @ReactMethod
    public final void getAllNativeTimestamps(Promise promise) {
        int t10;
        q.g(promise, "promise");
        try {
            ArrayList<TTIMetrics.Timing> timings = TTIMetrics.INSTANCE.getTimings();
            t10 = k.t(timings, 10);
            ArrayList arrayList = new ArrayList(t10);
            for (TTIMetrics.Timing timing : timings) {
                arrayList.add(NativeMapExtensionsKt.nativeMapOf(x.a("label", timing.getLabel()), x.a("timestamp", Long.valueOf(timing.getTimestamp())), x.a("tag", timing.getTag()), x.a("autoGenerated", Boolean.valueOf(timing.getAutoGenerated()))));
            }
            promise.resolve(NativeArrayExtensionsKt.toNativeArray(arrayList));
        } catch (Throwable th2) {
            promise.reject(th2);
        }
    }

    @Override // com.facebook.react.bridge.BaseJavaModule
    public Map<String, Long> getConstants() {
        Map<String, Long> l10;
        l10 = v.l(x.a("AppOpenedTimestamp", Long.valueOf(TTILoggingApplication.Companion.getAppOpenedTimestamp$tti_manager_release())));
        return l10;
    }

    @ReactMethod
    public final void getJSBundleTimestamps(Promise promise) {
        q.g(promise, "promise");
        try {
            ReactMarkerListener reactMarkerListener = ReactMarkerListener.INSTANCE;
            promise.resolve(NativeMapExtensionsKt.nativeMapOf(x.a("JSBundleStartedTimestamp", Double.valueOf(reactMarkerListener.getBundleStartedTimestamp())), x.a("JSBundleLoadedTimestamp", Double.valueOf(reactMarkerListener.getBundleLoadedTimestamp())), x.a("JSBundleParsedTimestamp", Double.valueOf(reactMarkerListener.getBundleParsedTimestamp()))));
        } catch (Throwable th2) {
            promise.reject(th2);
        }
    }

    @Override // com.facebook.react.bridge.NativeModule
    public String getName() {
        return "TTIManager";
    }

    @ReactMethod
    public final void logToDevice(String value) {
        q.g(value, "value");
        Log.i$default(Log.INSTANCE, "ttidata", value, (Throwable) null, 4, (Object) null);
    }

    @ReactMethod
    public final void logToDeviceEnabled(Promise promise) {
        q.g(promise, "promise");
        promise.resolve(BuildConfig.logTTIMetrics);
    }

    @ReactMethod(isBlockingSynchronousMethod = true)
    public final boolean runningTTIAutomation() {
        Boolean logTTIMetrics = BuildConfig.logTTIMetrics;
        q.f(logTTIMetrics, "logTTIMetrics");
        return logTTIMetrics.booleanValue();
    }

    @ReactMethod
    public final void trackTTILogged() {
        TTIMetrics.INSTANCE.setLoggedTTI(true);
    }
}
