package com.discord.tti_manager;

import co.discord.media_engine.b;
import com.facebook.react.modules.core.TimingModule;
import java.util.ArrayList;
import java.util.List;
import kotlin.Metadata;
import kotlin.jvm.internal.q;

@Metadata(d1 = {"\u0000>\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010!\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\t\n\u0002\b\u0002\n\u0002\u0010\u000b\n\u0002\b\u0002\bÆ\u0002\u0018\u00002\u00020\u0001:\u0001\u0013B\u0007\b\u0002¢\u0006\u0002\u0010\u0002J&\u0010\u0006\u001a\"\u0012\f\u0012\n \b*\u0004\u0018\u00010\u00050\u00050\u0007j\u0010\u0012\f\u0012\n \b*\u0004\u0018\u00010\u00050\u0005`\tJ.\u0010\n\u001a\u00020\u000b2\u0006\u0010\f\u001a\u00020\r2\b\b\u0002\u0010\u000e\u001a\u00020\u000f2\n\b\u0002\u0010\u0010\u001a\u0004\u0018\u00010\r2\b\b\u0002\u0010\u0011\u001a\u00020\u0012R\u0014\u0010\u0003\u001a\b\u0012\u0004\u0012\u00020\u00050\u0004X\u0082\u0004¢\u0006\u0002\n\u0000¨\u0006\u0014"}, d2 = {"Lcom/discord/tti_manager/TTIMetrics;", "", "()V", "timings", "", "Lcom/discord/tti_manager/TTIMetrics$Timing;", "getTimings", "Ljava/util/ArrayList;", "kotlin.jvm.PlatformType", "Lkotlin/collections/ArrayList;", "record", "", "label", "", "timestamp", "", "tag", "autoGenerated", "", TimingModule.NAME, "tti_manager_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
/* loaded from: classes5.dex */
public final class TTIMetrics {
    public static final TTIMetrics INSTANCE = new TTIMetrics();
    private static final List<Timing> timings = new ArrayList();

    @Metadata(d1 = {"\u0000(\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\t\n\u0002\b\u0002\n\u0002\u0010\u000b\n\u0002\b\u0010\n\u0002\u0010\b\n\u0002\b\u0002\b\u0086\b\u0018\u00002\u00020\u0001B'\u0012\u0006\u0010\u0002\u001a\u00020\u0003\u0012\u0006\u0010\u0004\u001a\u00020\u0005\u0012\b\u0010\u0006\u001a\u0004\u0018\u00010\u0003\u0012\u0006\u0010\u0007\u001a\u00020\b¢\u0006\u0002\u0010\tJ\t\u0010\u0011\u001a\u00020\u0003HÆ\u0003J\t\u0010\u0012\u001a\u00020\u0005HÆ\u0003J\u000b\u0010\u0013\u001a\u0004\u0018\u00010\u0003HÆ\u0003J\t\u0010\u0014\u001a\u00020\bHÆ\u0003J3\u0010\u0015\u001a\u00020\u00002\b\b\u0002\u0010\u0002\u001a\u00020\u00032\b\b\u0002\u0010\u0004\u001a\u00020\u00052\n\b\u0002\u0010\u0006\u001a\u0004\u0018\u00010\u00032\b\b\u0002\u0010\u0007\u001a\u00020\bHÆ\u0001J\u0013\u0010\u0016\u001a\u00020\b2\b\u0010\u0017\u001a\u0004\u0018\u00010\u0001HÖ\u0003J\t\u0010\u0018\u001a\u00020\u0019HÖ\u0001J\t\u0010\u001a\u001a\u00020\u0003HÖ\u0001R\u0011\u0010\u0007\u001a\u00020\b¢\u0006\b\n\u0000\u001a\u0004\b\n\u0010\u000bR\u0011\u0010\u0002\u001a\u00020\u0003¢\u0006\b\n\u0000\u001a\u0004\b\f\u0010\rR\u0013\u0010\u0006\u001a\u0004\u0018\u00010\u0003¢\u0006\b\n\u0000\u001a\u0004\b\u000e\u0010\rR\u0011\u0010\u0004\u001a\u00020\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u000f\u0010\u0010¨\u0006\u001b"}, d2 = {"Lcom/discord/tti_manager/TTIMetrics$Timing;", "", "label", "", "timestamp", "", "tag", "autoGenerated", "", "(Ljava/lang/String;JLjava/lang/String;Z)V", "getAutoGenerated", "()Z", "getLabel", "()Ljava/lang/String;", "getTag", "getTimestamp", "()J", "component1", "component2", "component3", "component4", "copy", "equals", "other", "hashCode", "", "toString", "tti_manager_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
    /* loaded from: classes5.dex */
    public static final class Timing {
        private final boolean autoGenerated;
        private final String label;
        private final String tag;
        private final long timestamp;

        public Timing(String label, long j10, String str, boolean z10) {
            q.g(label, "label");
            this.label = label;
            this.timestamp = j10;
            this.tag = str;
            this.autoGenerated = z10;
        }

        public static /* synthetic */ Timing copy$default(Timing timing, String str, long j10, String str2, boolean z10, int i10, Object obj) {
            if ((i10 & 1) != 0) {
                str = timing.label;
            }
            if ((i10 & 2) != 0) {
                j10 = timing.timestamp;
            }
            if ((i10 & 4) != 0) {
                str2 = timing.tag;
            }
            if ((i10 & 8) != 0) {
                z10 = timing.autoGenerated;
            }
            return timing.copy(str, j10, str2, z10);
        }

        public final String component1() {
            return this.label;
        }

        public final long component2() {
            return this.timestamp;
        }

        public final String component3() {
            return this.tag;
        }

        public final boolean component4() {
            return this.autoGenerated;
        }

        public final Timing copy(String label, long j10, String str, boolean z10) {
            q.g(label, "label");
            return new Timing(label, j10, str, z10);
        }

        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (!(obj instanceof Timing)) {
                return false;
            }
            Timing timing = (Timing) obj;
            return q.b(this.label, timing.label) && this.timestamp == timing.timestamp && q.b(this.tag, timing.tag) && this.autoGenerated == timing.autoGenerated;
        }

        public final boolean getAutoGenerated() {
            return this.autoGenerated;
        }

        public final String getLabel() {
            return this.label;
        }

        public final String getTag() {
            return this.tag;
        }

        public final long getTimestamp() {
            return this.timestamp;
        }

        public int hashCode() {
            int hashCode = ((this.label.hashCode() * 31) + b.a(this.timestamp)) * 31;
            String str = this.tag;
            int hashCode2 = (hashCode + (str == null ? 0 : str.hashCode())) * 31;
            boolean z10 = this.autoGenerated;
            if (z10) {
                z10 = true;
            }
            int i10 = z10 ? 1 : 0;
            int i11 = z10 ? 1 : 0;
            int i12 = z10 ? 1 : 0;
            return hashCode2 + i10;
        }

        public String toString() {
            String str = this.label;
            long j10 = this.timestamp;
            String str2 = this.tag;
            boolean z10 = this.autoGenerated;
            return "Timing(label=" + str + ", timestamp=" + j10 + ", tag=" + str2 + ", autoGenerated=" + z10 + ")";
        }
    }

    private TTIMetrics() {
    }

    public static /* synthetic */ void record$default(TTIMetrics tTIMetrics, String str, long j10, String str2, boolean z10, int i10, Object obj) {
        if ((i10 & 2) != 0) {
            j10 = System.currentTimeMillis();
        }
        if ((i10 & 4) != 0) {
            str2 = null;
        }
        if ((i10 & 8) != 0) {
            z10 = false;
        }
        tTIMetrics.record(str, j10, str2, z10);
    }

    public final synchronized ArrayList<Timing> getTimings() {
        return new ArrayList<>(timings);
    }

    public final synchronized void record(String label, long j10, String str, boolean z10) {
        q.g(label, "label");
        timings.add(new Timing(label, j10, str, z10));
    }
}
